lessons:
  outputs:
    dev:
      dataset: dbt_cr
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: bold-tooling-456903-i1
      threads: 60
      type: bigquery
  target: dev